version: '3'

services:
  # Nginx web server
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf

  # PHP Environment  
  php:
    image: php:7-fpm
    volumes:
      - ./:/app